name: tb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_core: 2.32.0
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  http: ^1.2.1
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  url_launcher: ^6.3.0
  provider: ^6.1.2
  firebase_auth: ^4.20.0
  firebase_ui_auth: ^1.14.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
